name: CI

on: push

jobs:
  test-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: PREPARE SYSTEM
      run: |
        python --version
        gfortran --version
        gcov --version
        sudo apt install graphviz
        # pip install --upgrade ford && ford --version
        pip install --upgrade FoBiS.py && FoBiS.py --version
    
    - name: CHECKOUT
      id: checkout
      run: |
        git clone --recursive https://github.com/szaghi/FLAP ./
        git log -n 1
        tag=`git tag | tail -n 1`
        echo "RELEASE=$tag" >> $GITHUB_ENV

    # - name: MAKE COVERAGE
    #   run: |
    #     cd FLAP
    #     FoBiS.py rule -ex makecoverage

    - name: MAKE TAR
      run: |
        echo "repository release version:" ${{ env.RELEASE }}
        FoBiS.py rule -ex maketar
        mv FLAP.tar.gz FLAP-${{ env.RELEASE }}.tar.gz
        ls *.tar.gz

    - name: DEPLOY ASSET
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # automatic_release_tag: "latest"
        # prerelease: true
        automatic_release_tag: ${{ env.RELEASE }}
        prerelease: false
        title: ${{ env.RELEASE }}
        files: |
          FLAP*.tar.gz

    # - name: DEPLOY ASSET
    #   uses: alexellis/upload-assets@0.2.2
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     asset_paths: '["./FLAP-*.tar.gz"]'
      # uses: ncipollo/release-action@v1
      # with:
      #   artifacts: "FLAP-*.tar.gz"
      #   token: ${{ secrets.GITHUB_TOKEN }}
      # uses: softprops/action-gh-release@v1
      # # if: startsWith(github.ref, 'refs/tags/')
      # with:
      #   tag_name: ${{steps.previous_tag.outputs.tag}}
      #   files: |
      #     FLAP-*.tar.gz
      # env:
      #     GITHUB_TOKEN: ${{ github.token }}


    # - name: MAKE DOC
    #   run: |
    #     cd FLAP
    #     FoBiS.py rule -ex makedoc
