name: CI

on: push

jobs:
  test-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: PREPARE SYSTEM
      run: |
        python --version
        gfortran --version
        gcov --version
        sudo apt install graphviz
        # pip install --upgrade ford && ford --version
        pip install --upgrade FoBiS.py && FoBiS.py --version
    
    - name: CHECKOUT
      id: checkout
      run: |
        git clone --recursive https://github.com/$GITHUB_REPOSITORY ./
        git log -n 1
        tag=`git tag | tail -n 1`
        echo "RELEASE=$tag" >> $GITHUB_ENV

    - name: MAKE COVERAGE
      run: |
        FoBiS.py rule -ex makecoverage

    - name: MAKE TAR
      run: |
        echo "release version:" ${{ env.RELEASE }}
        FoBiS.py rule -ex maketar
        ls *.tar.gz

    - name: DEPLOY ASSET
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.RELEASE }}
        prerelease: false
        title: ${{ env.RELEASE }}
        files: |
          *.tar.gz
          ./scripts/install.sh

    # - name: MAKE DOC
    #   run: |
    #     FoBiS.py rule -ex makedoc
